version: "3.9"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    ports:
      - 3000:3005
    environment:
      - WATCHPACK_POLLING=true